# Generated by Django 2.1.4 on 2019-01-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friendship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('creator', 'friend')},
        ),
    ]
