# Generated by Django 2.1.4 on 2019-01-11 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friends',
            field=models.ManyToManyField(related_name='_friendlist_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
