# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_players', models.IntegerField(default=8, editable=False)),
                ('rounds', models.IntegerField(default=7, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('round_one', models.IntegerField(blank=True, null=True)),
                ('round_two', models.IntegerField(blank=True, null=True)),
                ('round_three', models.IntegerField(blank=True, null=True)),
                ('round_four', models.IntegerField(blank=True, null=True)),
                ('round_five', models.IntegerField(blank=True, null=True)),
                ('round_six', models.IntegerField(blank=True, null=True)),
                ('round_seven', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_and_run.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
