# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books_and_run', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('player', 'game')]),
        ),
    ]
