# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 04:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books_and_run', '0002_auto_20170214_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_won', models.IntegerField(blank=True, null=True)),
                ('hands_won', models.IntegerField(blank=True, null=True)),
                ('games_played', models.IntegerField(blank=True, null=True)),
                ('high_score', models.IntegerField(blank=True, null=True)),
                ('low_score', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
