# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_and_run', '0005_auto_20170330_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='hands_won',
            field=models.IntegerField(default=0),
        ),
    ]
